import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348718/purritos/kyotPeek_w2hzr1.jpg",
    isLiked: false,
    title: "Exquisite Blanket",
    color: "brown",
    prevPrice:"18999",
    price: 18000,
    reviews: "3439",
    rating: 4.6,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348719/purritos/pawPlainBlanky_trnkba.png",
    isLiked: true,
    title: "Phenomenal soft blanket",
    color: "grey",
    prevPrice:"",
    price: 13500,
    reviews: "1431",
    rating: 4.3,
    categoryName: "plain-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348697/purritos/whiteFluffBall_vywkzv.png",
    isLiked: false,
    title: "Phenomenal soft blanket",
    color: "grey",
    prevPrice:"14999",
    price: 11999,
    reviews: "629",
    rating: 4.8,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348704/purritos/kyotComfy_pzgcmt.jpg",
    isLiked: true,
    title: "Thin all weather blanket",
    color: "grey",
    prevPrice:"",
    price: 9500,
    reviews: "439",
    rating: 2.4,
    categoryName: "plain-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348722/purritos/kyotAsleep2_nyidyy.jpg",
    isLiked: false,
    title: "Precious striped Blanket",
    color: "brown",
    prevPrice:"9999",
    price: 8000,
    reviews: "341",
    rating: 3.3,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348707/purritos/sleepPatternBlanket_uc0n6i.png",
    isLiked: false,
    title: "Exquisite designer blanket",
    color: "golden",
    prevPrice:"18999",
    price: 14999,
    reviews: "439",
    rating: 4.8,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348696/purritos/unknown_pcwtwg.png",
    isLiked: false,
    title: "Ferocious blanket",
    color: "white",
    prevPrice:"18999",
    price: 14999,
    reviews: "837",
    rating: 4.3,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348721/purritos/sleepPlainBlanket_cxzrst.png",
    isLiked: true,
    title: "Ultra-Soft thin blanket",
    color: "white",
    prevPrice:"",
    price: 7800,
    reviews: "721",
    rating: 2.5,
    categoryName: "plain-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348712/purritos/sweaterGrey2_sbepm0.png",
    isLiked: false,
    title: "Ultra-Soft sweater",
    color: "grey",
    prevPrice:"",
    price: 11999,
    reviews: "439",
    rating: 2.8,
    categoryName: "sweaters",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348714/purritos/ultraThinBlanky_aa4aow.png",
    isLiked: true,
    title: "Ultra Thin catsheet",
    color: "white",
    prevPrice:"",
    price: 6500,
    reviews: "439",
    rating: 1.6,
    categoryName: "plain-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348706/purritos/kyotHugCat_dldvh4.jpg",
    isLiked: false,
    title: "Ultra-soft Sweater",
    color: "brown",
    prevPrice:"18999",
    price: 11999,
    reviews: "1372",
    rating: 3.9,
    categoryName: "sweaters",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348697/purritos/woolBed_okej7t.png",
    isLiked: true,
    title: "Baba White Sheep wool",
    color: "white",
    prevPrice:"",
    price: 9500,
    reviews: "621",
    rating: 2.9,
    categoryName: "plain-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348710/purritos/sweaterBasket_lua3f4.png",
    isLiked: false,
    title: "Soft white Sweater",
    color: "white",
    prevPrice:"",
    price: 13400,
    reviews: "23",
    rating: 5,
    categoryName: "sweaters",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348711/purritos/sweaterGrey_tvx79o.png",
    isLiked: false,
    title: "Ultra-Soft sweater",
    color: "grey",
    prevPrice:"",
    price: 11999,
    reviews: "439",
    rating: 3.6,
    categoryName: "sweaters",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348701/purritos/bluPattern_zmbzpl.png",
    isLiked: false,
    title: "Exquisite Thin catsheet",
    color: "blue",
    prevPrice:"12399",
    price: 8399,
    reviews: "39",
    rating: 4.1,
    categoryName: "pattern-blankets",
  },
  {
    _id: uuid(),
    imageUrl: "https://res.cloudinary.com/ddqawrqs1/image/upload/v1649348698/purritos/catSweater_jcjdrl.png",
    isLiked: false,
    title: "Cat Turtle Neck Sweater",
    color: "white",
    prevPrice:"",
    price: 13400,
    reviews: "1183",
    rating: 4.7,
    categoryName: "sweaters",
  },
];
